/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajo_parquimetro;// carpeta que contiene las clases del proyecto

// importarcion/libreria de una clase propia de java
import java.net.URL;
import java.time.LocalDate; // esta clase maneja las fechas
import java.time.LocalTime; // esta clase maneja las horas
import java.time.format.DateTimeFormatter; // formatea las fechas(dia:mes:año)
import java.util.ArrayList;// lista de arreglos
import javax.swing.DefaultListModel;// esta clase es un modelo de lista, en la cual puedo ingresar un arreglo o un objeto (clase) 
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;// levanta/muestra un panel donde  puedes poner mensaje con opciones 

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    //nuestra clase la convertimos en un modelo de objeto list para poder ocupar el jlist de java
    DefaultListModel Modelo1 = new DefaultListModel();//letra A
    //hice una lista de arreglo de parquimetros ( lo que hace esto, es que cada lista ingresamos un objeto parquimetro)
    ArrayList<Parquimetro> Modelo = new ArrayList<>(); //letra A
    //variable "bandera", esta cuentas los click's, de los objetos seleccionados en la jlist
    public int selected = 0;
    //instanciacion de la clase funciones
    Funciones fun = new Funciones();

    //clase principal
    public Home() {
        //cuando se inica esta, le damos los valores de su contenido
        initComponents();
        this.setTitle("Sistema RATA PARQ");
        URL iconURL = getClass().getResource("/imagenes/icon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

        // settear el modelo 1 a la jlist, por defecto va a estar vacio, ya que arriba lo inciamos sin darle valores ( letra A)
        Lista.setModel(Modelo1);
        //centrar el contenedor u aplicacion
        setLocationRelativeTo(null);
        //toma la fecha del sistema 
        LocalDate fecha = LocalDate.now();
        // setteamos en una etiqueta en formato local
        lblFecha.setText(fecha.format(DateTimeFormatter.ISO_LOCAL_DATE));
        // aqui se toma la hora del sistema
        LocalTime ahora = LocalTime.now();
        // obtenemos las variables de hora y minuto
        int horas = ahora.getHour();
        int minutos = ahora.getMinute();
        // validamos que del 1 al 9 se le agruegue un cero antes (0), ya que ocuparemos la variable como cadena(string)
        String hours = "";
        if (horas < 10) {
            hours = "0" + horas;
        } else {
            hours = "" + horas;
        }
        //agregamos los valores a las cajas de textos
        txtHora.setText(hours);
        txtMinutos.setText(minutos + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //se llaman todas las clases que ocupa java, para crear una aplicacion de escritorio, esto es por defecto
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTitle = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtRun = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        comboTipo = new javax.swing.JComboBox<>();
        comboVisa = new javax.swing.JComboBox<>();
        txtNacionalidad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCobrar.setText("COBRAR");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        jLabel8.setText("PLACA PATENTE:");

        jLabel9.setText("TIPO:");

        jLabel10.setText("COLOR:");

        jLabel11.setText("MARCA:");

        jLabel12.setText("HORA ENTRADA:");

        jTitle.setText("REGISTRO DE VEHICULOS \"RATA PARQ\"");

        txtHora.setText("20");

        jLabel3.setText("RUN:");

        txtMinutos.setText("30");

        jLabel4.setText("NOMBRE:");

        jLabel5.setText("APELLIDOS:");

        lblFecha.setText("00/00/0000");

        jLabel6.setText("EDAD:");

        jLabel14.setText("Hrs.-");

        jLabel7.setText("NACIONALIDAD:");

        jLabel15.setText(":");

        jLabel13.setText("VISA:");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        Lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(Lista);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE VEHICULO", "AUTOMOVIL", "BUS", "CAMIONETA", "CAMION", "FURGON", "MOTOCICLETA" }));

        comboVisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "VISA TURISTA", "VISA SUJETA A CONTRATO", "VISA DE ESTUDIANTE", "VISA TEMPORAL", "VISA DEFINITIVA" }));

        txtNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHILENO", "EXTRANJERO" }));

        jLabel1.setText("Valor Minuto:");

        txtValor.setText("20");

        btnEliminar.setText("ELIMINAR VEHICULO SELECCIONADO");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRun)
                            .addComponent(txtApellidos)
                            .addComponent(txtEdad)
                            .addComponent(comboVisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPatente)
                                    .addComponent(txtMarca)
                                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtColor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnGuardar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCobrar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTitle)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btnGuardar)
                    .addComponent(btnCobrar)
                    .addComponent(comboVisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //sea crean las variables que voy a utilizar en el boton de guardar
        String Errores = "";
        String run = txtRun.getText();
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        int edad = 0;
        // aqui valide que la edad sea numerica, por eso se utilizo try-catch
        try {
            edad = Integer.parseInt(txtEdad.getText());
        } catch (NumberFormatException e) {
            Errores += edad;
        }
        // aqui se utiliza un jcombobox para listar las nacionalidades 
        String nacionalidad = txtNacionalidad.getSelectedItem().toString();
        // aqui se utiliza un jcombobox 
        String visa = comboVisa.getSelectedItem().toString();
        // aqui se utiliza un jtextfield
        String patente = txtPatente.getText();
        // aqui se utiliza un jcombobox
        String tipo = comboTipo.getSelectedItem().toString();
        // aqui se validan los errores a traves del if's
        if ("SELECCIONE VEHICULO".equals(tipo)) {
            Errores += tipo;
        }
        if (nacionalidad != "CHILENO" && visa == "SELECCIONAR") {
            Errores += " " + visa;
        } else if (nacionalidad == "CHILENO" && visa != "SELECCIONAR") {
            Errores += visa;
        }
        if (!fun.validarRut(run)) {
            Errores += run;
        }
        // aqui se utiliza un jtextfield
        String color = txtColor.getText();
        String marca = txtMarca.getText();
        String hora = txtHora.getText();
        // validamos que el largo de cadena sea menor a 2 y que le agruegue un cero antes (0) si es 1 , ya que ocuparemos la variable como cadena(string) 
        if (hora.length() < 2) {
            hora = "0" + hora;
        }
        // validamos que el largo de cadena sea menor a 2 y que le agruegue un cero antes (0) si es 1 , ya que ocuparemos la variable como cadena(string) 
        String minuto = txtMinutos.getText();
        if (minuto.length() < 2) {
            minuto = "0" + minuto;
        }
        // se concatena la hora y minuto
        String entrada = hora + ":" + minuto;
        // aqui validamos que la variable errores este vacia para poder guardar
        if (Errores.isEmpty()) {
            //se inicializa la clase parquimetro con el constructor con parametros
            Parquimetro parking = new Parquimetro(patente, tipo, color, marca, run, nombre, apellidos, edad, nacionalidad, visa, entrada);
            //agregamos el objeto parquimetro a la lista de modelo (defaultmodellist) con la funcion addelement
            // su indice empieza de cero
            Modelo1.addElement(parking);
            //aqui volvemos agregar el objeto parquimetro al arraylist<class> por la funcion add
            //su indice empieza de 1
            Modelo.add(parking);
            //setteamos el modelo1, que seria la lista de modelo, ya que el modelo de arreglo de lista no es soportado por la jlist
            Lista.setModel(Modelo1);
        } else {
            //muestra los errores de la variable error en caso de haberlos, en un mensaje de dialogo
            JOptionPane.showMessageDialog(rootPane, "*Revise su Selección de vehiculo.\n"
                    + "*Revise la Selección de Visa." + "\n*Revise que el Run esté Correcto."
                    + "\n*Revise que la Edad este en Formato númerico.", "ATENCIÓN!", JOptionPane.WARNING_MESSAGE);
        }
        //incrementa los numeros de registro, tomando el tamaño del arraylist<class>
        jTitle.setText("REGISTRO DE VEHICULOS RATA PARQ: " + Modelo.size() + " Vehiculos Aparcados.");
    }//GEN-LAST:event_btnGuardarActionPerformed


    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        // nuevemente validamos que la lista no este vacia y a partir de su indice obtenemos una instancia
        //de la clase parquimetro de la cual podemos obtener los datos a traves de los getters
        if (!Lista.isSelectionEmpty()) {
            Parquimetro par = Modelo.get(Lista.getSelectedIndex());
            // aqui se toma la hora del sistema para calcular la hora de salida y realizar cobro
            // no se puso la opcion de eliminar inmediatamente al realizar el cobro, ya que todas las aplicaciones(capa 8) pueden presentar error
            //asi que se opto por eliminar un registro al hacer click
            LocalTime salida = LocalTime.now();
            int hora = salida.getHour();
            String h = String.valueOf(hora);
            if (hora < 10) {
                h = "0" + hora;
            } else {
                h = "" + hora;
            }
            int min = salida.getMinute();
            String m = String.valueOf(min);
            if (min < 10) {
                m = "0" + min;
            } else {
                m = "" + min;
            }
            int h_s = fun.calcularMinutos(par.getHora_entrada(), h + ":" + m);
            int valor = Integer.parseInt(txtValor.getText());
            int cobro = h_s * valor;
            String mensaje = "El ";
            //SELECCIONE VEHICULO, AUTOMOVIL, BUS, CAMIONETA, CAMION, FURGON, MOTOCICLETA
            if (par.getTipo().equals("MOTOCICLETA") || par.getTipo().equals("CAMIONETA")) {
                mensaje = "La " + par.getTipo() + "\nPlaca Patente" + par.getPlaca() + "\nDebe Pagar: $" + cobro + ".-"
                        + "\n por " + h_s + " minutos.";
            } else {
                mensaje += par.getTipo() + "\nPlaca Patente" + par.getPlaca() + "\nDebe Pagar: $" + cobro + ".-"
                        + "\n por " + h_s + " minutos.";
            }
            // se muestran los datos necesario para el cobro
            JOptionPane.showMessageDialog(rootPane, mensaje);
        } else { //vacio
            JOptionPane.showMessageDialog(rootPane, "No Existen Registros, \nDebe Agregar Datos para Poder Seleccionar la Lista!", "ATENCIÓN!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        //validamos que la lista no este vacia y removemos el indice retornado de los modelos
        if (!Lista.isSelectionEmpty()) {
            Modelo1.remove(Lista.getSelectedIndex());
            Modelo.remove(Lista.getSelectedIndex() + 1);
            Lista.setModel(Modelo1);
            JOptionPane.showMessageDialog(rootPane, "Se ha Eliminado un Registro!\n");
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Existen Registros, \nDebe Agregar Datos para Poder Seleccionar la Lista!", "ATENCIÓN!", JOptionPane.WARNING_MESSAGE);
        }
        //decrementa/dismuye/elimina los numeros de registro, tomando el tamaño del arraylist<class>
        jTitle.setText("REGISTRO DE VEHICULOS RATA PARQ: " + Modelo.size() + " Vehiculos Aparcados.");

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    // hace que corra la aplicacion
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboVisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitle;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JComboBox<String> txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPatente;
    private javax.swing.JTextField txtRun;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
